version: '3.9'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - cuviq-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    networks:
      - cuviq-network
    depends_on:
      - backend

networks:
  cuviq-network:
    driver: bridge
